### ISSUE TITLE
Token refresh handler

### ISSUE THREAD

**Issue by msmoljan** [nodes-android/okhttputils#3]
Implement an Authenticator for handling 401 responses when a token needs to be refreshed.

**Comment by msmoljan** [comment]
You can adjust the following class for this purpose: 
https://github.com/nodes-projects/tally-android/blob/0bdf216850a37dd418395e3a8fb6221e8b088d24/common-modules/rest/src/main/java/com/tally/tallyapp/rest/TokenAuthenticator.kt#L18

**Comment by markusrubey** [comment]
Done. See #4
